services:
  postgres:
    image: postgres:17
    container_name: Ranked-DB-Postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: RankedAdmin
      POSTGRES_PASSWORD: RankedAdmin1234##
      POSTGRES_DB: ranked
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
