services:
  postgres:
    image: postgres:17
    container_name: Ranked-DB-Postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: RankedAdmin
      POSTGRES_PASSWORD: RankedAdmin1234##
      POSTGRES_DB: ranked
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis/redis-stack:latest
    container_name: Ranked-Redis-Stack
    restart: always
    ports:
      - "6379:6379"     # Redis
      - "8001:8001"     # RedisInsight (UI)
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
